#define UERR_SUCCESS 0

#define UERR_FAILURE -50

#define UERR_MEMORY_ALLOCATE_FAILURE -1

#define UERR_CURL_FAILURE -2
#define UERR_STRSTR_FAILURE -5
#define UERR_M3U8_UNTERMINATED_STRING_LITERAL -6

#define UERR_JSON_CANNOT_PARSE -7
#define UERR_JSON_MISSING_REQUIRED_KEY -8
#define UERR_JSON_NON_MATCHING_TYPE -9

#define UERR_ATTACHMENT_DRM_FAILURE -10
#define UERR_NO_STREAMS_AVAILABLE -11
#define UERR_TIDY_FAILURE -12
#define UERR_HOTMART_SESSION_EXPIRED -13
#define UERR_M3U8_PARSE_FAILURE -14
#define UERR_M3U8_MISSING_REQUIRED_ATTRIBUTE -14

const char* strurr(const int code);
