name: Build

on:
  push:
    branches:
        - '**'

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Enable Debian unstable repository
      run: |
        sudo bash -c "echo 'deb https://deb.debian.org/debian/ unstable main contrib' >> '/etc/apt/sources.list'"
        sudo apt -o Acquire::AllowInsecureRepositories=true update
        sudo apt -o Dpkg::Options::="--force-overwrite" --assume-yes --allow-unauthenticated install libc6
    - name: Setup Linux cross compiler
      run: |
        sudo apt install --assume-yes --allow-unauthenticated \
            gcc-arm-linux-gnueabi \
            gcc-arm-linux-gnueabihf \
            gcc-aarch64-linux-gnu \
            gcc-i686-linux-gnu \
            gcc-powerpc-linux-gnu \
            gcc-powerpc64-linux-gnu \
            gcc-powerpc64le-linux-gnu \
            gcc-s390x-linux-gnu \
            gcc-mips-linux-gnu \
            gcc-mips64-linux-gnuabi64 \
            gcc-mips64el-linux-gnuabi64 \
            gcc-mipsel-linux-gnu \
            gcc-mipsisa32r6-linux-gnu \
            gcc-mipsisa32r6el-linux-gnu \
            gcc-mipsisa64r6-linux-gnuabi64 \
            gcc-mipsisa64r6el-linux-gnuabi64 \
            gcc-sparc64-linux-gnu \
            gcc-riscv64-linux-gnu \
            gcc-alpha-linux-gnu \
            gcc-hppa-linux-gnu \
            gcc-m68k-linux-gnu \
            gcc-sh4-linux-gnu \
            gcc-x86-64-linux-gnux32
    - name: Setup Android cross compiler
      uses: nttld/setup-ndk@main
      id: setup-ndk
      with:
        ndk-version: r25c
    - name: Post setup settings for Android cross compiler
      run: |
        echo 'ANDROID_HOME=${{ steps.setup-ndk.outputs.ndk-path }}' >> "${GITHUB_ENV}"
        sudo sed -i '/CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG/d' /usr/local/share/cmake-*/Modules/Platform/Android.cmake
        echo '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin' >> "${GITHUB_PATH}"
    - name: Setup Windows cross compiler
      run: |
        declare -r LLVM_MINGW_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --retry 10 --retry-delay 3 --silent --url 'https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest')")"
        declare -r LLVM_MINGW_TARBALL='/tmp/llvm-mingw.tar.xz'
        declare -r LLVM_MINGW_URL="https://github.com/mstorsjo/llvm-mingw/releases/download/${LLVM_MINGW_TAG}/llvm-mingw-${LLVM_MINGW_TAG}-msvcrt-ubuntu-18.04-x86_64.tar.xz"
        
        curl --retry 10 --retry-delay 3 --silent --location --url "${LLVM_MINGW_URL}" --output "${LLVM_MINGW_TARBALL}"
        tar --directory="$(dirname "${LLVM_MINGW_TARBALL}")" --extract --file="${LLVM_MINGW_TARBALL}"
        
        echo "LLVM_MINGW_HOME=$(dirname "${LLVM_MINGW_TARBALL}")/$(basename "${LLVM_MINGW_URL}" '.tar.xz')" >> "${GITHUB_ENV}"
        echo "$(dirname "${LLVM_MINGW_TARBALL}")/$(basename "${LLVM_MINGW_URL}" '.tar.xz')/bin" >> "${GITHUB_PATH}"
    - name: Setup MacOS X cross compiler
      run: |
        git clone --depth='1' 'https://github.com/tpoechtrager/osxcross.git'
        
        curl --retry 10 --retry-delay 3 --silent --location --url 'https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz' --output './osxcross/tarballs/MacOSX11.3.sdk.tar.xz'
        
        cd './osxcross'
        
        CMAKE_BUILD_PARALLEL_LEVEL='100' SDK_VERSION='11.3' OSX_VERSION_MIN='10.6' ./build.sh <<< ''
        
        echo "OSXCROSS_HOME=$(realpath './target')" >> "${GITHUB_ENV}"
        echo "$(realpath './target/bin')" >> "${GITHUB_PATH}"
    - name: Setup NetBSD cross compiler
      run: | 
        declare -r NETBSD_CROSS_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --retry 10 --retry-delay 3 --silent --url 'https://api.github.com/repos/AmanoTeam/n3tbsdcr0ss/releases/latest')")"
        declare -r NETBSD_CROSS_TARBALL='/tmp/netbsd-cross.tar.xz'
        declare -r NETBSD_CROSS_URL="https://github.com/AmanoTeam/n3tbsdcr0ss/releases/download/${NETBSD_CROSS_TAG}/x86_64-linux-gnu.tar.xz"
        
        curl --retry 10 --retry-delay 3 --silent --location --url "${NETBSD_CROSS_URL}" --output "${NETBSD_CROSS_TARBALL}"
        tar --directory="$(dirname "${NETBSD_CROSS_TARBALL}")" --extract --file="${NETBSD_CROSS_TARBALL}"
        
        echo 'NETBSD_TOOLCHAIN=/tmp/unknown-unknown-netbsd' >> "${GITHUB_ENV}"
        echo '/tmp/unknown-unknown-netbsd/bin' >> "${GITHUB_PATH}"
    - name: Setup FreeBSD cross compiler
      run: |
        declare -r FREEBSD_CROSS_TAG="$(jq --raw-output '.tag_name' <<< "$(curl  --retry 10 --retry-delay 3 --silent --url 'https://api.github.com/repos/AmanoTeam/fr33bsdcr0ss/releases/latest')")"
        declare -r FREEBSD_CROSS_TARBALL='/tmp/freebsd-cross.tar.xz'
        declare -r FREEBSD_CROSS_URL="https://github.com/AmanoTeam/fr33bsdcr0ss/releases/download/${FREEBSD_CROSS_TAG}/x86_64-linux-gnu.tar.xz"
        
        curl --silent --retry 10 --retry-delay 3 --location --url "${FREEBSD_CROSS_URL}" --output "${FREEBSD_CROSS_TARBALL}"
        tar --directory="$(dirname "${FREEBSD_CROSS_TARBALL}")" --extract --file="${FREEBSD_CROSS_TARBALL}"
        
        echo 'FREEBSD_TOOLCHAIN=/tmp/unknown-unknown-freebsd' >> "${GITHUB_ENV}"
        echo '/tmp/unknown-unknown-freebsd/bin' >> "${GITHUB_PATH}"
    - name: Setup DragonFly cross compiler
      run: |
        declare -r DRAGONFLY_CROSS_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --retry 10 --retry-delay 3 --silent --url 'https://api.github.com/repos/AmanoTeam/dr4g0nflybsdcr0ss/releases/latest')")"
        declare -r DRAGONFLY_CROSS_TARBALL='/tmp/freebsd-cross.tar.xz'
        declare -r DRAGONFLY_CROSS_URL="https://github.com/AmanoTeam/dr4g0nflybsdcr0ss/releases/download/${DRAGONFLY_CROSS_TAG}/x86_64-linux-gnu.tar.xz"
        
        curl --retry 10 --retry-delay 3 --silent --location --url "${DRAGONFLY_CROSS_URL}" --output "${DRAGONFLY_CROSS_TARBALL}"
        tar --directory="$(dirname "${DRAGONFLY_CROSS_TARBALL}")" --extract --file="${DRAGONFLY_CROSS_TARBALL}"
        
        echo 'DRAGONFLY_TOOLCHAIN=/tmp/unknown-unknown-dragonfly' >> "${GITHUB_ENV}"
        echo '/tmp/unknown-unknown-dragonfly/bin' >> "${GITHUB_PATH}"
    - name: Setup Haiku cross compiler
      run: |
        declare -r HAIKU_CROSS_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --retry 10 --retry-delay 3 --silent --url 'https://api.github.com/repos/AmanoTeam/h4ikucr0ss/releases/latest')")"
        declare -r HAIKU_CROSS_TARBALL='/tmp/haiku-cross.tar.xz'
        declare -r HAIKU_CROSS_URL="https://github.com/AmanoTeam/h4ikucr0ss/releases/download/${HAIKU_CROSS_TAG}/x86_64-linux-gnu.tar.xz"
        
        curl --retry 10 --retry-delay 3 --silent --location --url "${HAIKU_CROSS_URL}" --output "${HAIKU_CROSS_TARBALL}"
        tar --directory="$(dirname "${HAIKU_CROSS_TARBALL}")" --extract --file="${HAIKU_CROSS_TARBALL}"
        
        echo 'HAIKU_TOOLCHAIN=/tmp/unknown-unknown-haiku' >> "${GITHUB_ENV}"
        echo '/tmp/unknown-unknown-haiku/bin' >> "${GITHUB_PATH}"
    - name: Setup OBGGCC cross compiler
      run: |
        declare -r OBGGCC_CROSS_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --retry 10 --retry-delay 3 --silent --url 'https://api.github.com/repos/AmanoTeam/obggcc/releases/latest')")"
        declare -r OBGGCC_CROSS_TARBALL='/tmp/linux-cross.tar.xz'
        declare -r OBGGCC_CROSS_URL="https://github.com/AmanoTeam/obggcc/releases/download/${OBGGCC_CROSS_TAG}/x86_64-linux-gnu.tar.xz"
        
        curl --retry 10 --retry-delay 3 --silent --location --url "${OBGGCC_CROSS_URL}" --output "${OBGGCC_CROSS_TARBALL}"
        tar --directory="$(dirname "${OBGGCC_CROSS_TARBALL}")" --extract --file="${OBGGCC_CROSS_TARBALL}"
        
        echo 'OBGGCC_TOOLCHAIN=/tmp/unknown-unknown-linux' >> "${GITHUB_ENV}"
        echo '/tmp/unknown-unknown-linux/bin' >> "${GITHUB_PATH}"
    - name: Setup OpenBSD cross compiler
      run: |
        declare -r OPENBSD_CROSS_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --retry 10 --retry-delay 3 --silent --url 'https://api.github.com/repos/AmanoTeam/0p3nbsdcr0ss/releases/latest')")"
        declare -r OPENBSD_CROSS_TARBALL='/tmp/openbsd-cross.tar.xz'
        declare -r OPENBSD_CROSS_URL="https://github.com/AmanoTeam/0p3nbsdcr0ss/releases/download/${OPENBSD_CROSS_TAG}/x86_64-linux-gnu.tar.xz"
        
        curl --retry 10 --retry-delay 3 --silent --location --url "${OPENBSD_CROSS_URL}" --output "${OPENBSD_CROSS_TARBALL}"
        tar --directory="$(dirname "${OPENBSD_CROSS_TARBALL}")" --extract --file="${OPENBSD_CROSS_TARBALL}"
        
        echo 'OPENBSD_TOOLCHAIN=/tmp/unknown-unknown-openbsd' >> "${GITHUB_ENV}"
        echo '/tmp/unknown-unknown-openbsd/bin' >> "${GITHUB_PATH}"
    - name: Build with CMake
      run: |
        declare -r MACHINE_HOST="$(gcc -dumpmachine)"
        
        declare -r targets=(
            "${MACHINE_HOST}"
            arm-linux-gnueabi
            arm-unknown-linux-gnueabi
            arm-linux-gnueabihf
            arm-unknown-linux-gnueabihf
            armv7-w64-mingw32
            armv7a-linux-androideabi
            powerpc-linux-gnu
            powerpc-unknown-netbsd
            powerpc-unknown-linux-gnu
            i686-linux-android
            i686-linux-gnu
            i486-unknown-linux-gnu
            i686-w64-mingw32
            i386-unknown-netbsdelf
            i386-unknown-freebsd
            i386-unknown-openbsd
            sh4-linux-gnu
            shle-unknown-netbsdelf
            m68k-linux-gnu
            hppa-linux-gnu
            hppa-unknown-netbsd
            hppa-unknown-linux-gnu
            # hppa-unknown-openbsd
            alpha-linux-gnu
            alpha-unknown-netbsd
            alpha-unknown-openbsd
            alpha-unknown-linux-gnu
            mipsisa32r6el-linux-gnu
            mipsisa32r6-linux-gnu
            mipsel-linux-gnu
            mips-linux-gnu
            mips-unknown-netbsd
            mipsel-unknown-linux-gnu
            mips-unknown-linux-gnu
            x86_64-apple-darwin
            x86_64h-apple-darwin
            x86_64-linux-android
            x86_64-w64-mingw32
            x86_64-unknown-netbsd
            x86_64-unknown-freebsd
            x86_64-unknown-dragonfly
            x86_64-unknown-haiku
            x86_64-linux-gnux32
            x86_64-unknown-linux-gnu
            x86_64-unknown-openbsd
            aarch64-linux-android
            aarch64-linux-gnu
            aarch64-w64-mingw32
            aarch64-apple-darwin
            aarch64-unknown-freebsd
            aarch64-unknown-linux-gnu
            powerpc64-linux-gnu
            powerpc64le-linux-gnu
            powerpc-unknown-freebsd
            powerpc64-unknown-freebsd
            powerpc64le-unknown-linux-gnu
            s390x-linux-gnu
            s390x-unknown-linux-gnu
            s390-unknown-linux-gnu
            riscv64-linux-gnu
            riscv64-unknown-freebsd
            sparc64-linux-gnu
            sparc64-unknown-freebsd
            sparc64-unknown-netbsd
            sparc-unknown-netbsdelf
            sparc-unknown-linux-gnu
            mipsisa64r6el-linux-gnuabi64
            mipsisa64r6-linux-gnuabi64
            mips64-linux-gnuabi64
            mips64el-linux-gnuabi64
            mips64el-unknown-linux-gnuabi64
            # vax-unknown-netbsdelf
        )
        
        declare -r OUTPUT_DIRECTORY="$(realpath './output')"
        
        mkdir --parent "${OUTPUT_DIRECTORY}"
        mkdir build && cd build
        
        for target in "${targets[@]}"; do
            echo "Building for ${target}"

            declare SPARKLEC_ENABLE_LTO=ON

            if [[ "${target}" == *-apple-darwin ]]; then
                SPARKLEC_ENABLE_LTO=OFF
            fi

            if [ "${target}" == "${MACHINE_HOST}" ]; then
                cmake -Wno-dev \
                    -DCMAKE_C_COMPILER='/usr/bin/clang' \
                    -DSPARKLEC_ENABLE_LTO="${SPARKLEC_ENABLE_LTO}" \
                    -DCMAKE_INSTALL_PREFIX="${target}" \
                    -DCMAKE_BUILD_TYPE=MinSizeRel ../ 1>/dev/null
            else
                cmake -Wno-dev \
                    -DSPARKLEC_ENABLE_LTO="${SPARKLEC_ENABLE_LTO}" \
                    -DCMAKE_TOOLCHAIN_FILE="./.github/workflows/cmake_toolchains/${target}.cmake" \
                    -DCMAKE_INSTALL_PREFIX="${target}" \
                    -DCMAKE_BUILD_TYPE=MinSizeRel ../ 1>/dev/null
            fi
            
            pushd './ffmpeg-build'
            make --jobs 1>/dev/null
            pushd
            
            cmake --build ./ --target ffmpeg -- --jobs=1 1>/dev/null
            cmake --build ./ --target bearssl -- --jobs 1>/dev/null
            cmake --build ./ -- --jobs 1>/dev/null
            cmake --install ./ 1>/dev/null
            
            if [[ "${target}" == *'mingw32' ]]; then
                zip --recurse-paths -9 "${OUTPUT_DIRECTORY}/${target}.zip" "${target}" 1>/dev/null
            else
                tar --create --file=- "${target}" |  xz --compress -9 > "${OUTPUT_DIRECTORY}/${target}.tar.xz"
            fi
            
            rm --force --recursive ./*
        done
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        path: ./output
    - name: Get tag name for release
      if: startsWith(github.event.head_commit.message, 'Bump version')
      run: echo "VERSION_TAG=${COMMIT_MESSAGE/* }" >> "${GITHUB_ENV}"
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    - name: Create release
      if: startsWith(github.event.head_commit.message, 'Bump version')
      uses: softprops/action-gh-release@master
      with:
        tag_name: v${{ env.VERSION_TAG }}
        name: SparkleC v${{ env.VERSION_TAG }}
        files: ./output/*
        draft: true
        prerelease: false
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
