name: Build

on:
  push:
    branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: true
    - name: Setup Linux cross compiler
      run: |
        sudo apt update
        sudo apt install --assume-yes gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu gcc-i686-linux-gnu
    - name: Setup Android cross compiler
      uses: nttld/setup-ndk@main
      id: setup-ndk
      with:
        ndk-version: r25b
    - name: Post setup settings for Android cross compiler
      run: |
        echo 'ANDROID_HOME=${{ steps.setup-ndk.outputs.ndk-path }}' >> "${GITHUB_ENV}"
        sudo sed -i '/CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG/d' /usr/local/share/cmake-*/Modules/Platform/Android.cmake
    - name: Setup Windows cross compiler
      run: |
        declare -r LLVM_MINGW_TAG="$(jq --raw-output '.tag_name' <<< "$(curl --silent --url 'https://api.github.com/repos/mstorsjo/llvm-mingw/releases/latest')")"
        declare -r LLVM_MINGW_TARBALL='/tmp/llvm-mingw.tar.xz'
        declare -r LLVM_MINGW_URL="https://github.com/mstorsjo/llvm-mingw/releases/download/${LLVM_MINGW_TAG}/llvm-mingw-${LLVM_MINGW_TAG}-msvcrt-ubuntu-18.04-x86_64.tar.xz"
        
        curl --silent --location --url "${LLVM_MINGW_URL}" --output "${LLVM_MINGW_TARBALL}"
        tar --directory="$(dirname "${LLVM_MINGW_TARBALL}")" --extract --file="${LLVM_MINGW_TARBALL}"
        
        echo "LLVM_MINGW_HOME=$(dirname "${LLVM_MINGW_TARBALL}")/$(basename "${LLVM_MINGW_URL}" '.tar.xz')" >> "${GITHUB_ENV}"
    - name: Setup MacOS X cross compiler
      run: |
        git clone --depth='1' 'https://github.com/tpoechtrager/osxcross.git'
        
        curl --silent --location --url 'https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz' --output './osxcross/tarballs/MacOSX11.3.sdk.tar.xz'
        
        cd './osxcross'
        
        CMAKE_BUILD_PARALLEL_LEVEL='30' SDK_VERSION='11.3' OSX_VERSION_MIN='10.6' ./build.sh <<< ''
        
        echo "OSXCROSS_HOME=$(realpath './target')" >> "${GITHUB_ENV}"
    - name: Build with CMake
      run: |
        declare -r MACHINE_HOST="$(gcc -dumpmachine)"
        
        declare -r targets=(
            aarch64-linux-android
            aarch64-linux-gnu
            aarch64-w64-mingw32
            aarch64-apple-darwin
            arm-linux-gnueabi
            armv7-w64-mingw32
            armv7a-linux-androideabi
            i686-linux-android
            i686-linux-gnu
            i686-w64-mingw32
            x86_64-apple-darwin
            x86_64h-apple-darwin
            x86_64-linux-android
            x86_64-w64-mingw32
            "${MACHINE_HOST}"
        )
        
        declare -r OUTPUT_DIRECTORY="$(realpath './output')"
        
        mkdir --parent "${OUTPUT_DIRECTORY}"
        mkdir build && cd build
        
        for target in "${targets[@]}"; do
            echo "Building for ${target}"
            
            if [ "${target}" == "${MACHINE_HOST}" ]; then
                cmake -Wno-dev \
                    -DSPARKLEC_ENABLE_LTO=ON \
                    -DCMAKE_INSTALL_PREFIX="${target}" \
                    -DCMAKE_BUILD_TYPE=MinSizeRel ../ 1>/dev/null
            else
                cmake -Wno-dev \
                    -DSPARKLEC_ENABLE_LTO=ON \
                    -DCMAKE_TOOLCHAIN_FILE="./.github/workflows/cmake_toolchains/${target}.cmake" \
                    -DCMAKE_INSTALL_PREFIX="${target}" \
                    -DCMAKE_BUILD_TYPE=MinSizeRel ../ 1>/dev/null
            fi
            
            cmake --build ./ --target bearssl -- --jobs=50 1>/dev/null
            cmake --build ./ -- --jobs=50 1>/dev/null
            cmake --install ./ 1>/dev/null
            
            if [[ "${target}" == *'mingw32' ]]; then
                zip --recurse-paths -9 "${OUTPUT_DIRECTORY}/${target}.zip" "${target}" 1>/dev/null
            else
                tar --create --file=- "${target}" |  xz --compress -9 > "${OUTPUT_DIRECTORY}/${target}.tar.xz"
            fi
            
            rm --force --recursive ./*
        done
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        path: ./output